#!/bin/bash

CONFIG=/etc/service/scalyr-agent-2/agent.json

if [[ -n ${SCALYR_API_KEY+x} ]]; then
    appname=${AWSEBEnvironmentName:-steemit-dev-jussi}
    instid=$(wget --timeout=5 -q -O - http://169.254.169.254/latest/meta-data/instance-id)
    scalyr_hostname=${appname}-${instid:-jussi}-internal
    export scalyr_hostname
    echo "starting scalyr-agent with scalyr_hostname=$scalyr_hostname"
    exec 2>&1 scalyr-agent-2 --no-fork --config-file="${CONFIG}" start
fi
