#!/bin/bash -e


CPU_COUNT="$(grep -c processor /proc/cpuinfo)"


cd "${APP_ROOT}"
exec 2>&1 \
  chpst -u www-data \
    pipenv run python3.6 -m "${APP_CMD}" \
      --debug "${JUSSI_DEBUG:-False}" \
      --server_host "${JUSSI_SERVER_HOST}" \
      --server_port "${JUSSI_SERVER_PORT}" \
      --server_workers "${JUSSI_SERVER_WORKERS:-$CPU_COUNT}" \
      --REQUEST_MAX_SIZE "${JUSSI_REQUEST_MAX_SIZE:-600_000}" \
      --REQUEST_TIMEOUT "${JUSSI_REQUEST_TIMEOUT:-3}" \
      --KEEP_ALIVE "${JUSSI_KEEP_ALIVE:-True}" \
      --websocket_pool_minsize "${JUSSI_WEBSOCKET_POOL_MINSIZE:-8}" \
      --websocket_pool_maxsize "${JUSSI_WEBSOCKET_POOL_MAXSIZE:-8}" \
      --websocket_pool_recycle "${JUSSI_WESOCKET_POOL_RECYCLE:- -1}" \
      --source_commit "${SOURCE_COMMIT}" \
      --docker_tag "${DOCKER_TAG}" \
      --upstream_hivemind_url "${JUSSI_HIVEMIND_HTTP_URL}" \
      --upstream_overseer_url "${JUSSI_OVERSEER_HTTP_URL}" \
      --upstream_sbds_url "${JUSSI_SBDS_HTTP_URL}" \
      --upstream_steemd_url "${JUSSI_STEEMD_WS_URL}" \
      --upstream_yo_url "${JUSSI_YO_HTTP_URL}" \
      --redis_host "${JUSSI_REDIS_HOST}" \
      --redis_port "${JUSSI_REDIS_PORT:-6379}" \
      --redis_namespace "${JUSSI_REDIS_NAMESPACE:-jussi}" \
      --statsd_host "${JUSSI_STATSD_HOST}" \
      --statsd_port "${JUSSI_STATSD_PORT:-8125}" \
      --statsd_prefix "${JUSSI_STATSD_PREFIX:-jussi}" \
      2>&1
