#!/bin/bash -e


CPU_COUNT="$(grep -c processor /proc/cpuinfo)"


cd "${APP_ROOT}"
exec 2>&1 \
  chpst -u www-data \
    pipenv run python3.6 -m "${APP_CMD}" \
      --debug "${JUSSI_DEBUG:-False}" \
      --server_host "${JUSSI_SERVER_HOST}" \
      --server_port "${JUSSI_SERVER_PORT}" \
      --server_workers "${JUSSI_SERVER_WORKERS:-$CPU_COUNT}" \
      --REQUEST_MAX_SIZE "${JUSSI_REQUEST_MAX_SIZE:-6_000_000}" \
      --REQUEST_TIMEOUT "${JUSSI_REQUEST_TIMEOUT:- 11}" \
      --KEEP_ALIVE "${JUSSI_KEEP_ALIVE:-True}" \
      --websocket_pool_minsize "${JUSSI_WEBSOCKET_POOL_MINSIZE:-8}" \
      --websocket_pool_maxsize "${JUSSI_WEBSOCKET_POOL_MAXSIZE:-8}" \
      --websocket_pool_recycle "${JUSSI_WESOCKET_POOL_RECYCLE:- -1}" \
      --websocket_queue_size "${JUSSI_WESOCKET_QUEUE_SIZE:- 0}" \
      --source_commit "${SOURCE_COMMIT}" \
      --docker_tag "${DOCKER_TAG}" \
      --upstream_config_file "${JUSSI_UPSTREAM_CONFIG_FILE:- PROD_UPSTREAM_CONFIG.json}" \
      --test_upstream_urls "${JUSSI_TEST_UPSTREAM_URLS:- True}" \
      --cache_read_timeout "${JUSSI_CACHE_READ_TIMEOUT:-0.5}" \
      --redis_host "${JUSSI_REDIS_HOST}" \
      --redis_port "${JUSSI_REDIS_PORT:-6379}" \
      --redis_pool_minsize "${JUSSI_REDIS_POOL_MINSIZE:-1}" \
      --redis_pool_maxsize "${JUSSI_REDIS_POOL_MAXSIZE:-30}" \
      --redis_read_replica_hosts "${JUSSI_REDIS_READ_REPLICA_HOSTS}"
